zhihudaily/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from peewee import Model, CharField

from zhihudaily.configs import Config


class BaseModel(Model):
    class Meta:
        database = Config.database


class Zhihudaily(BaseModel):
    date = CharField()
    json_news = CharField()
    display_date = CharField()


def create_tables():
    Config.database.connect()
    Config.database.create_table(Zhihudaily)

zhihudaily/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

zhihudaily/app.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from flask import Flask
from werkzeug.utils import import_string


extensions = [
    'zhihudaily.cache:cache',
    'zhihudaily.sentry:sentry_wrapper',
]

blueprints = [
    'zhihudaily.views.utils:utils',
    'zhihudaily.views.index:text_ui',
    'zhihudaily.views.with_image:image_ui',
    'zhihudaily.views.pages:pages_ui',
    'zhihudaily.views.three_columns:three_columns_ui',
]


def create_app(config):
    app = Flask('zhihudaily')
    app.config.from_object(config)

    for extention in extensions:
        extention = import_string(extention)
        extention.init_app(app)

    for blueprint in blueprints:
        blueprint = import_string(blueprint)
        app.register_blueprint(blueprint)

    @app.context_processor
    def inject_statics():
        return dict(debug=config.DEBUG)

    return app

zhihudaily/views/feeds.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from werkzeug.contrib.atom import AtomFeed
from flask import request, Blueprint, json

from zhihudaily.cache import cache
from zhihudaily.configs import Config
from zhihudaily.models import Zhihudaily
from zhihudaily.utils import Date
from zhihudaily.crawler import Crawler
from zhihudaily._compat import urljoin


# This is the feeds blueprint, but it is deprecated now.
feeds = Blueprint('feeds', __name__, template_folder='templates')
redis_server = Config.redis_server


@feeds.route('/feeds')
@cache.cached(timeout=1200)
def generate_feed():
    """Code snippet from https://flask.pocoo.org/snippets/10/"""
    day = Date()
    feed = AtomFeed('Zhihudaily', feed_url=request.url, url=request.url_root)
    news = Zhihudaily.get(Zhihudaily.date == int(day.today))

    articles = json.loads(news.json_news)
    for article in articles:
        if redis_server.get(article['url']):
            body = redis_server.get(article['url']).decode('utf-8')
        else:
            body = Crawler().send_request(article['url']).json()['body']
            redis_server.setex(article['url'], (60*60*24), body)
        feed.add(article['title'], body,
                 content_type='html',
                 author='zhihudaily',
                 url=urljoin(request.url_root, article['url']),
                 updated=day.now)
    return feed.get_response()

zhihudaily/views/index.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from flask import render_template, Blueprint, request, redirect, url_for, json

from zhihudaily.utils import Date
from zhihudaily.cache import cache
from zhihudaily.models import Zhihudaily


text_ui = Blueprint('text_ui', __name__, template_folder='templates')


@text_ui.route('/')
@cache.cached(timeout=900)
def index():
    """The index page, for 文字 UI."""
    news = Zhihudaily.select().order_by(Zhihudaily.date.desc()).first()
    day = Date(news.date)

    return render_template("index.html",
                           lists=json.loads(news.json_news),
                           display_date=news.display_date,
                           day_before=day.day_before)


def full_request_path():
    """Make a key that includes GET parameters."""
    return request.full_path


@text_ui.route('/news/<date>')
@cache.cached(timeout=900, key_prefix=full_request_path)
def before(date):
    """For 文字 UI and 图片 UI, before today."""

    day = Date(date)
    if day.today <= date:
        if request.args.get('image', 'False') == 'True':
            return redirect(url_for('image_ui.with_image'))
        else:
            return redirect(url_for('text_ui.index'))

    news = Zhihudaily.get(Zhihudaily.date == date)

    template_name = {
        'False': 'index.html', 'True': 'with_image.html'
    }[request.args.get('image', 'False')]

    return render_template(template_name,
                           lists=json.loads(news.json_news),
                           display_date=news.display_date,
                           day_before=day.day_before,
                           day_after=day.day_after)


@text_ui.errorhandler(Zhihudaily.DoesNotExist)
def handle_record_not_exist(e):
    return render_template("not_found.html")

zhihudaily/views/pages.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from flask import render_template, Blueprint, json
from flask_paginate import Pagination

from zhihudaily.models import Zhihudaily
from zhihudaily.cache import cache


pages_ui = Blueprint('pages_ui', __name__, template_folder='templates')


@pages_ui.route('/pages', defaults={'page': 1})
@pages_ui.route('/pages/<int:page>')
@cache.cached(timeout=900)
def pages(page):
    """The page the 分页 UI."""
    db_news_list = (Zhihudaily.select()
                              .order_by(Zhihudaily.date.desc())
                              .paginate(page, 4))
    records = [
        {"news": json.loads(news.json_news), "display_date": news.display_date}
        for news in db_news_list
    ]
    pagination = Pagination(page=page, total=Zhihudaily.select().count(),
                            per_page=4, inner_window=7, outer_window=3,
                            css_framework='bootstrap3')

    return render_template('pages.html',
                           records=records,
                           pagination=pagination)

zhihudaily/views/three_columns.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from flask import render_template, jsonify, Blueprint, json

from zhihudaily.models import Zhihudaily
from zhihudaily.utils import Date
from zhihudaily.cache import cache
from zhihudaily.crawler import Crawler


three_columns_ui = Blueprint('three_columns_ui', __name__,
                             template_folder='templates')


@three_columns_ui.route('/three-columns')
@cache.cached(timeout=3600)
def three_columns():
    """The page for 三栏 UI"""
    day = Date()
    days = day.date_range(20)
    return render_template('three_columns.html', days=days)


@three_columns_ui.route('/three-columns/<date>')
@cache.cached(timeout=900)
def show_titles(date):
    """Get titles via AJAX."""
    try:
        news = Zhihudaily.get(Zhihudaily.date == date)
        json_news = json.loads(news.json_news)
    except Zhihudaily.DoesNotExist:
        json_news = []
    return jsonify(news=json_news)


@three_columns_ui.route('/three-columns/append-date/<date>')
@cache.cached(timeout=10800)
def append_date(date):
    """Append dates when scroll to bottom via AJAX"""
    day = Date(date)
    append_list = day.date_range(16)[1:]
    return jsonify(append_list=append_list)


@three_columns_ui.route('/three-columns/contents/<id>')
@cache.cached(timeout=10800)
def get_content(id):
    r = Crawler().send_request('https://news-at.zhihu.com/api/4/news/' + id)
    return jsonify(body=r.json()['body'])

zhihudaily/views/utils.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import

from flask import send_file, g, Blueprint

from zhihudaily.configs import Config
from zhihudaily.crawler import Crawler
from zhihudaily._compat import StringIO


utils = Blueprint('utils', __name__)


@utils.before_app_request
def before_request():
    g.db = Config.database
    g.db.connect()


@utils.after_app_request
def after_request(response):
    g.db.close()
    return response


@utils.route('/img/<server>/<path:hash_string>')
def image(server, hash_string):
    """Handle image, use redis to cache image."""
    image_url = 'https://{0}.zhimg.com/{1}'.format(server, hash_string)
    cached = Config.redis_server.get(image_url)
    if cached:
        buffer_image = StringIO(cached)
        buffer_image.seek(0)
    else:
        r = Crawler().send_request(image_url)
        buffer_image = StringIO(r.content)
        buffer_image.seek(0)
        Config.redis_server.setex(image_url, (60*60*24*4),
                                  buffer_image.getvalue())
    return send_file(buffer_image, mimetype='image/jpeg')

zhihudaily/views/with_image.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import


from flask import render_template, Blueprint, json

from zhihudaily.cache import cache
from zhihudaily.models import Zhihudaily
from zhihudaily.utils import Date


image_ui = Blueprint('image_ui', __name__, template_folder='templates')


@image_ui.route('/withimage')
@cache.cached(timeout=900)
def with_image():
    """The page for 图片 UI."""
    news = Zhihudaily.select().order_by(Zhihudaily.date.desc()).first()
    day = Date(news.date)

    return render_template('with_image.html',
                           lists=json.loads(news.json_news),
                           display_date=news.display_date,
                           day_before=day.day_before)

zhihudaily/templates/base.html
{% from 'macros.html' import nav_link with context %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Zhihu Daily</title>
    {% block head %}
    <link rel=stylesheet type=text/css href="https://cdn.bootcss.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/zhihudaily.css') }}">
    {% endblock %}
  </head>
  
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">知乎日报</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {{ nav_link('text_ui.index', '文字 UI') }}
          {{ nav_link('image_ui.with_image', '图片 UI') }}
          {{ nav_link('pages_ui.pages', '分页 UI') }}
          {{ nav_link('three_columns_ui.three_columns', '三栏 UI') }}
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-->
  </nav>
  {% block body %}{% endblock %}
  <div class="footer text-center">
    <p>With love made by lord63. Fork me on <a href="https://github.com/lord63/zhihudaily">github</a>.</p>
  </div>
  {% block js %}
    <script src="https://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    {% if not debug %}
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-69622009-1', 'auto');
        ga('send', 'pageview');
      </script>
    {% endif %}
  {% endblock %}
</html>

zhihudaily/templates/index.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
      <h3 class="text-center">{{ display_date }}</h3>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
      <ul class="list-group">
        {% for item in lists %}
        <li class="list-group-item">
              <a href={{ item['share_url'] }} class="">{{ item['title'] }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-3 col-md-6 col-xs-12">
      {% if day_before >= '20130519' %}
      <ul class="nav nav-pills pull-left">
        <li role="presentation">
          <a href="{{ url_for('text_ui.before', date=day_before, image=False) }}"><<< Previous</a>
        </li>
      </ul>
      {% endif %}
      {% if day_after %}
      <ul class="nav nav-pills pull-right">
        <li role="presentation">
          <a href="{{ url_for('text_ui.before', date=day_after, image=False) }}">Next >>></a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

zhihudaily/templates/layout.html
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <title>知乎日报</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" aria-controls="navbar" data-target="#hd-nav" data-toggle="collapase">
            <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
          </button>
          <h3 id="logo">知乎日报</h3>
        </div>
        <div id="hd-nav" class="navbar-collapse collapse" aria-expanded="false">
          <ul class="nav navbar-nav navbar-right text-center">
            {{ nav_link('text_ui.index', '文字 UI') }}
            {{ nav_link('image_ui.with_image', '图片 UI') }}
            {{ nav_link('pages_ui.pages', '分页 UI') }}
            {{ nav_link('three_columns_ui.three_columns', '三栏 UI') }}
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>

zhihudaily/templates/macros.html
{% macro nav_link(endpoint, text) %}
{% if request.endpoint.endswith(endpoint) %}
  <li role="presentation" class="active"><a href="{{ url_for(endpoint) }}">{{ text }}</a></li>
{% else %}
  <li role="presentation"><a href="{{ url_for(endpoint) }}">{{ text }}</a></li>
{% endif %}
{% endmacro %}

zhihudaily/templates/not_found.html
{% extends "base.html" %}
{% block body %}
  <h3 class="text-center">Oops! Can't find the things you want.</h3>
{% endblock %}

zhihudaily/templates/pages.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  {% for record in records %}
  <div class="news_content">
    <h3>{{ record['display_date'] }}</h3><hr/>
    <div class="row">
      {% for item in record['news'] %}
        <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="thumbnail">
            <a href="{{ item['share_url'] }}"><img src="{{ item['image'] }}" class="img-responsive"></a>
            <div class="caption">
              <p>{{ item['title'] | truncate(25, True) }}</p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
      <div class="paginate">{{ pagination.links }}</div>
    </div>
  </div>
</div>
{% endblock %}

zhihudaily/templates/three_columns.html
{% extends "base.html" %}
{% block head %}
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/lib/stroll.min.css') }}">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/lib/zhihu_news.css') }}">
  {{ super() }}
{% endblock %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div class="stroll-list">
        <ul class="wave three-column-day">
          {% for day in days %}
          <li><a href="/three-columns/{{ day }}" class="days">{{ day }}</a></li>
          {% endfor %}
          <li class="load">Load More</li>
        </ul>
      </div>
    </div>
    <div class="col-md-4 title-col">
      <div class="stroll-list">
        <ul class="three-column-title"></ul>
      </div> 
    </div>
    <div class="col-md-6">
        <div class="three-column-content">
          <div class="main-wrap content-wrap"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
  {{ super() }}
  <script src="{{ url_for('static', filename='js/lib/stroll.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/lib/jquery.isloading.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/zhihudaily.js')  }}"></script>
{% endblock %}

zhihudaily/templates/with_image.html
{% extends "base.html" %}
{% block body %}
<div class="container">
  <div class="news_content">
  <h3>{{ display_date }}</h3><hr/>
  <div class="row">
    {# todo: refactor the image story item #}
    {% for item in lists %}
      <div class="col-md-3 col-sm-4 col-xs-6">
        <div class="thumbnail">
          <a href="{{ item['share_url'] }}"><img src="{{ item['image'] }}" class="img-responsive"></a>
          <div class="caption">
            <p>{{ item['title'] | truncate(25, True) }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="row">
    {# todo: refactor navbar #}
    <div class="col-md-12 col-sm-12 col-xs-12">
      {% if day_before >= '20130519' %}
      <ul class="nav nav-pills pull-left">
        <li role="presentation">
          <a href="{{ url_for('text_ui.before', date=day_before, image=True) }}"><<< Previous</a>
        </li>
      </ul>
      {% endif %}
      {% if day_after %}
      <ul class="nav nav-pills pull-right">
        <li role="presentation">
          <a href="{{ url_for('text_ui.before', date=day_after, image=True) }}">Next >>></a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>  
</div>
{% endblock %}